export const SEND_TEXT = "SEND_TEXT";
export const RECV_TEXT = "RECV_TEXT";
export const RECV_ACCESS_TOKEN = "RECV_ACCESS_TOKEN";
export const RECV_USER_INFO = "RECV_USER_INFO";
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const OPEN_DIALOG_CREATE_CHANNEL = "OPEN_DIALOG_CREATE_CHANNEL";